version: "3"


services:
  database:
    image: postgres
    container_name: database_students
    restart: always
    ports:
     - 4321:5432
    env_file:
     - ./back-end/.env
    volumes:
      - pg_students:/var/lib/postgresql/data

  app_node:
    container_name: node_students
    build: ./back-end
    ports:
     - 5000:5000
    env_file:
     - ./back-end/.env
    depends_on:
     - database

  app_react:
    build: ./front-end
    container_name: app_react
    volumes:
      - build_react:/var/www/html

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - build_react:/var/www/html
    depends_on:
      - app_react
      - app_node
      - database

volumes:
  build_react:
  pg_students:
