name: PullRequest
on: [pull_request]
jobs:
  PullRequest:
    runs-on: self-hosted
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_POSTGRES_USER: "postgres"
          envkey_POSTGRES_PASSWORD: "postgres"
          envkey_POSTGRES_DB: "students"
          envkey_DATABASE_URL: "postgresql://postgres:postgres@database_students:5432/students_test"
          file_name: .env.test
      - name: Run tests
        run: docker-compose -f docker-compose-test.yml run app_node npm run test
      - name: Build
        run: npm i && npm run build